### ISSUE TITLE
[URGENT] Unable to convert classes to dex format

### ISSUE THREAD

**Issue by oldnewuser2** [unity-plugins/Unity-Admob#122]
Hi all,
I am using unity 2017.4.21f1

My game already has the latest version of Google Mobile Ads SDK installed, used for serving Banner and Interstitial ads.

Also, I have integrated unity ads (through switching the button in services tab).

Now, I want to use Admob mediation with Unity Ads, therefore I have downloaded and imported the latest version of unity-admob adapter.

However, when I try to build the apk, I got the below message:

`CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_181\bin\java.exe -Xmx4096M -Dcom.android.sdkmanager.toolsdir="C:\Users\S\AppData\Local\Android\Sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/BuildConfig;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/IUnityAdsListener;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$FinishState;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$PlacementState;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$UnityAdsError;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/mediation/IUnityAdsExtendedListener;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/metadata/InAppPurchaseMetaData;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/metadata/MediationMetaData;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
	at com.android.dx.command.dexer.Main.main(Main.java:244)
	at com.android.dx.command.Main.main(Main.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:130)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)
	... 9 more
]
stdout[
processing archive C:\Users\S\Desktop\Unity Projects\SJA_v1.1.9_SDKTEST\Temp\StagingArea\android-libraries\GoogleAIDL\libs\.\classes.jar...
processing com/android/vending/billing/BuildConfig.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
processing archive C:\Users\S\Desktop\Unity Projects\SJA_v1.1.9_SDKTEST\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\libs\.\unity-plugin-library.jar...
processing com/google/unity/BuildConfig.class...
processing com/google/unity/ads/AdNetworkExtras.class...
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$10.class...
processing com/google/unity/ads/Banner$11.class...
processing com/google/unity/ads/Banner$12.class...
processing com/google/unity/ads/Banner$13.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$3$1.class...
processing com/google/unity/ads/Banner$3$2.class...
processing com/google/unity/ads/Banner$3$3.class...
processing com/google/unity/ads/Banner$3$4.class...
processing com/google/unity/ads/Banner$3$5.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/Banner$6.class...
processing com/google/unity/ads/Banner$7.class...
processing com/google/unity/ads/Banner$8.class...
processing com/google/unity/ads/Banner$9.class...
processing com/google/unity/ads/CustomNativeAd.class...
processing com/google/unity/ads/CustomNativeAd$1.class...
processing com/google/unity/ads/CustomNativeAd$2.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$1$1$1.class...
processing com/google/unity/ads/Interstitial$1$1$2.class...
processing com/google/unity/ads/Interstitial$1$1$3.class...
processing com/google/unity/ads/Interstitial$1$1$4.class...
processing com/google/unity/ads/Interstitial$1$1$5.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/NativeAdLoader.class...
processing com/google/unity/ads/NativeAdLoader$1.class...
processing com/google/unity/ads/NativeAdLoader$2.class...
processing com/google/unity/ads/NativeAdLoader$3.class...
processing com/google/unity/ads/NativeAdLoader$3$1.class...
processing com/google/unity/ads/NativeAdLoader$3$2.class...
processing com/google/unity/ads/NativeAdLoader$3$3.class...
processing com/google/unity/ads/NativeAdLoader$4.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1$2.class...
processing com/google/unity/ads/RewardBasedVideo$1$1$3.class...
processing com/google/unity/ads/RewardBasedVideo$1$1$4.class...
processing com/google/unity/ads/RewardBasedVideo$1$1$5.class...
processing com/google/unity/ads/RewardBasedVideo$1$1$6.class...
processing com/google/unity/ads/RewardBasedVideo$1$1$7.class...
processing com/google/unity/ads/RewardBasedVideo$1$1$8.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/RewardBasedVideo$4.class...
processing com/google/unity/ads/UnityAdListener.class...
processing com/google/unity/ads/UnityAdLoaderListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
processing archive C:\Users\S\Desktop\Unity Projects\SJA_v1.1.9_SDKTEST\Temp\StagingArea\android-libraries\GooglePlay\libs\.\classes.jar...
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$5.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$6.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$7.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$8.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$Features.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$2$1.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$3$1.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$5.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing com/unity/purchasing/googleplay/VRPurchaseActivity.class...
processing archive C:\Users\S\Desktop\Unity Projects\SJA_v1.1.9_SDKTEST\Temp\StagingArea\android-libraries\android.arch.lifecycle.runtime-1.0.0\libs\.\classes.jar...
processing android/arch/lifecycle/BuildConfig.class...
processing android/arch/lifecycle/LifecycleRegistry.class...
processing android/arch/lifecycle/LifecycleRegistry$1.class...
processing android/arch/lifecycle/LifecycleRegistry$ObserverWithState.class...
processing android/arch/lifecycle/LifecycleRegistryOwner.class...
processing android/arch/lifecycle/ReportFragment.class...
processing android/arch/lifecycle/ReportFragment$ActivityInitializationListener.class...
processing archive C:\Users\S\Desktop\Unity Projects\SJA_v1.1.9_SDKTEST\Temp\StagingArea\android-libraries\com.android.support.customtabs-26.1.0\libs\.\classes.jar...
processing android/support/customtabs/BuildConfig.class...
processing android/support/customtabs/CustomTabsCallback.class...
processing android/support/customtabs/CustomTabsClient.class...
processing android/support/customtabs/CustomTabsClient$1.class...
processing android/support/customtabs/CustomTabsClient$2.class...
processing android/support/customtabs/CustomTabsClient$2$1.class...
processing android/support/customtabs/CustomTabsClient$2$2.class...
processing android/support/customtabs/CustomTabsClient$2$3.class...
processing android/support/customtabs/CustomTabsClient$2$4.class...
processing android/support/customtabs/CustomTabsIntent.class...
processing android/support/customtabs/CustomTabsIntent$1.class...
processing android/support/customtabs/CustomTabsIntent$Builder.class...
processing android/support/customtabs/CustomTabsService.class...
processing android/support/customtabs/CustomTabsService$1.class...
processing android/support/customtabs/CustomTabsService$1$1.class...
processing android/support/customtabs/CustomTabsService$Result.class...
processing android/support/customtabs/CustomTabsServiceConnection.class...
processing android/support/customtabs/CustomTabsServiceConnection$1.class...
processing android/support/customtabs/CustomTabsSession.class...
processing android/support/customtabs/CustomTabsSessionToken.class...
processing android/support/customtabs/CustomTabsSessionToken$1.class...
processing android/support/customtabs/ICustomTabsCallback.class...
processing android/support/customtabs/ICustomTabsCallback$Stub.class...
processing android/support/customtabs/ICustomTabsCallback$Stub$Proxy.class...
processing android/support/customtabs/ICustomTabsService.class...
processing android/support/customtabs/ICustomTabsService$Stub.class...
processing android/support/customtabs/ICustomTabsService$Stub$Proxy.class...
processing android/support/customtabs/IPostMessageService.class...
processing android/support/customtabs/IPostMessageService$Stub.class...
processing android/support/customtabs/IPostMessageService$Stub$Proxy.class...
processing android/support/customtabs/PostMessageService.class...
processing android/support/customtabs/PostMessageService$1.class...
processing android/support/customtabs/PostMessageServiceConnection.class...
processing archive C:\Users\S\Desktop\Unity Projects\SJA_v1.1.9_SDKTEST\Temp\StagingArea\android-libraries\com.android.support.support-compat-26.1.0\libs\.\classes.jar...
processing android/support/compat/BuildConfig.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoApi16Impl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoApi18Impl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoBaseImpl.class...
processing android/support/v4/app/ActivityCompat.class...
processing android/support/v4/app/ActivityCompat$1.class...
processing android/support/v4/app/ActivityCompat$OnRequestPermissionsResultCallback.class...
processing android/support/v4/app/ActivityCompat$RequestPermissionsRequestCodeValidator.class...
processing android/support/v4/app/ActivityCompat$SharedElementCallback21Impl.class...
processing android/support/v4/app/ActivityCompat$SharedElementCallback23Impl.class...
processing android/support/v4/app/ActivityCompat$SharedElementCallback23Impl$1.class...
processing android/support/v4/app/ActivityManagerCompat.class...
processing android/support/v4/app/ActivityOptionsCompat.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsCompatApi16Impl.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsCompatApi23Impl.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsCompatApi24Impl.class...
processing android/support/v4/app/AlarmManagerCompat.class...
processing android/support/v4/app/AppOpsManagerCompat.class...
processing android/support/v4/app/BundleCompat.class...
processing android/support/v4/app/BundleCompat$BundleCompatBaseImpl.class...
processing android/support/v4/app/BundleUtil.class...
processing android/support/v4/app/INotificationSideChannel.class...
processing android/support/v4/app/INotificationSideChannel$Stub.class...
processing android/support/v4/app/INotificationSideChannel$Stub$Proxy.class...
processing android/support/v4/app/JobIntentService.class...
processing android/support/v4/app/JobIntentService$CommandProcessor.class...
processing android/support/v4/app/JobIntentService$CompatJobEngine.class...
processing android/support/v4/app/JobIntentService$CompatWorkEnqueuer.class...
processing android/support/v4/app/JobIntentService$CompatWorkItem.class...
processing android/support/v4/app/JobIntentService$GenericWorkItem.class...
processing android/support/v4/app/JobIntentService$JobServiceEngineImpl.class...
processing android/support/v4/app/JobIntentService$JobServiceEngineImpl$WrapperWorkItem.class...
processing android/support/v4/app/JobIntentService$JobWorkEnqueuer.class...
processing android/support/v4/app/JobIntentService$WorkEnqueuer.class...
processing android/support/v4/app/NotificationBuilderWithActions.class...
processing android/support/v4/app/NotificationBuilderWithBuilderAccessor.class...
processing android/support/v4/app/NotificationCompat.class...
processing android/support/v4/app/NotificationCompat$Action.class...
processing android/support/v4/app/NotificationCompat$Action$1.class...
processing android/support/v4/app/NotificationCompat$Action$Builder.class...
processing android/support/v4/app/NotificationCompat$Action$Extender.class...
processing android/support/v4/app/N<message truncated>`

Can some one please help me find what has gone wrong? Thank you.

**Comment by oldnewuser2** [comment]
I guess ALL Unity users that try to use Admob UnityAds adaptor will face this problem, and this problem has been complaint of numerous times on all sort of forums, it is surprising that no new versions of sdks or plugins have been released to try to solve this problem.

**Comment by unity-plugins** [comment]
UnityAds adapter was added default .
Related lib is 
unity-ads-sdk-2.1.aar and unity-adapter-2.1.0.0.aar 
If there was some error with this lib ,
you can replace this with new version adapter and unityads sdk  or 
you can delete this two aar to remove UnityAds and keep admob only
