### ISSUE TITLE
Unable to merge android manifests

### ISSUE THREAD

**Issue by dotWasim** [unity-plugins/Unity-Admob#14]
Hi, I was working with [google play services](https://github.com/playgameservices/play-games-plugin-for-unity) without any problem. after I add Admob, I start seeing this issue. I don't know what's the problem. I tried to search about it here, but I couldn't find any working solution. Can you help please?
#
```
 Error building Player: CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
 C:/Program Files/Java/jdk1.8.0_91\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Wasim-PC/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -
 
 stderr[
 Error: [Temp\StagingArea\AndroidManifest-main.xml:22, C:\Users\Wasim-PC\Documents\Fly With The Air\Temp\StagingArea\android-libraries\MainLibProj\AndroidManifest.xml:13] Trying to merge incompatible /manifest/application/meta-data[@name=com.google.android.gms.version] element:
   <meta-data
       @android:name="com.google.android.gms.version"
 --    @android:value="8115000">
   <meta-data
       @android:name="com.google.android.gms.version"
 ++    @android:value="@integer/google_play_services_version">
 Error: [Temp\StagingArea\AndroidManifest-main.xml:22, C:\Users\Wasim-PC\Documents\Fly With The Air\Temp\StagingArea\android-libraries\play-services-basement-9.2.1\AndroidManifest.xml:5] Trying to merge incompatible /manifest/application/meta-data[@name=com.google.android.gms.version] element:
   <meta-data
       @android:name="com.google.android.gms.version"
 --    @android:value="8115000">
   <meta-data
       @android:name="com.google.android.gms.version"
 ++    @android:value="@integer/google_play_services_version">
 ]
 stdout[
 
 ]

```

**Comment by unity-plugins** [comment]
Edit mainifest.xml in plugin folder,remove one of the following
<meta-data
       @android:name="com.google.android.gms.version"
    @android:value="8115000"/>


   <meta-data
       @android:name="com.google.android.gms.version"
   @android:value="@integer/google_play_services_version"/>

**Comment by dotWasim** [comment]
I rmoved this one
```
   <meta-data
   @android:name="com.google.android.gms.version"
       @android:value="@integer/google_play_services_version"/>
```

now it's showing different error.

`Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_91\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Wasim-PC/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorCompatHelper;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorListenerCompat;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
	... 9 more
]
stdout[
processing archive C:\Users\Wasim-PC\Documents\Fly With The Air\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/games/
ignored resource com/google/games/bridge/
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive C:\Users\Wasim-PC\Documents\Fly With The Air\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\bin\classes.jar...
ignored resource .readme
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource android/
ignored resource android/support/
ignored resource android/support/v7/
ignored resource android/support/v7/app/
processing android/support/v7/app/ActionBar.class...
processing android/support/v7/app/ActionBar$DisplayOptions.class...
processing android/support/v7/app/ActionBar$LayoutParams.class...
processing android/support/v7/app/ActionBar$NavigationMode.class...
processing android/support/v7/app/ActionBar$OnMenuVisibilityListener.class...
processing android/support/v7/app/ActionBar$OnNavigationListener.class...
processing android/support/v7/app/ActionBar$Tab.class...
processing android/support/v7/app/ActionBar$TabListener.class...
processing android/support/v7/app/ActionBarActivity.class...
processing android/support/v7/app/ActionBarDrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$1.class...
processing android/support/v7/app/ActionBarDrawerToggle$Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$DelegateProvider.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerArrowDrawableToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DummyDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$HoneycombDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$JellybeanMr2Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$ToolbarCompatDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggleHoneycomb.class...
processing android/support/v7/app/ActionBarDrawerToggleHoneycomb$SetIndicatorInfo.class...
processing android/support/v7/app/AlertController.class...
processing android/support/v7/app/AlertController$1.class...
processing android/support/v7/app/AlertController$2.class...
processing android/support/v7/app/AlertController$3.class...
processing android/support/v7/app/AlertController$4.class...
processing android/support/v7/app/AlertController$5.class...
processing android/support/v7/app/AlertController$AlertParams.class...
processing android/support/v7/app/AlertController$AlertParams$1.class...
processing android/support/v7/app/AlertController$AlertParams$2.class...
processing android/support/v7/app/AlertController$AlertParams$3.class...
processing android/support/v7/app/AlertController$AlertParams$4.class...
processing android/support/v7/app/AlertController$AlertParams$OnPrepareListViewListener.class...
processing android/support/v7/app/AlertController$ButtonHandler.class...
processing android/support/v7/app/AlertController$CheckedItemAdapter.class...
processing android/support/v7/app/AlertDialog.class...
processing android/support/v7/app/AlertDialog$Builder.class...
processing android/support/v7/app/AppCompatActivity.class...
processing android/support/v7/app/AppCompatCallback.class...
processing android/support/v7/app/AppCompatDelegate.class...
processing android/support/v7/app/AppCompatDelegateImplBase.class...
processing android/support/v7/app/AppCompatDelegateImplBase$1.class...
processing android/support/v7/app/AppCompatDelegateImplBase$ActionBarDrawableToggleImpl.class...
processing android/support/v7/app/AppCompatDelegateImplBase$AppCompatWindowCallbackBase.class...
processing android/support/v7/app/AppCompatDelegateImplV11.class...
processing android/support/v7/app/AppCompatDelegateImplV14.class...
processing android/support/v7/app/AppCompatDelegateImplV14$AppCompatWindowCallbackV14.class...
processing android/support/v7/app/AppCompatDelegateImplV23.class...
processing android/support/v7/app/AppCompatDelegateImplV23$AppCompatWindowCallbackV23.class...
processing android/support/v7/app/AppCompatDelegateImplV7.class...
processing android/support/v7/app/AppCompatDelegateImplV7$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$2.class...
processing android/support/v7/app/AppCompatDelegateImplV7$3.class...
processing android/support/v7/app/AppCompatDelegateImplV7$4.class...
processing android/support/v7/app/AppCompatDelegateImplV7$5.class...
processing android/support/v7/app/AppCompatDelegateImplV7$5$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$6.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionMenuPresenterCallback.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionModeCallbackWrapperV7$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ListMenuDecorView.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState$SavedState.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState$SavedState$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelMenuPresenterCallback.class...
processing android/support/v7/app/AppCompatDialog.class...
processing android/support/v7/app/AppCompatDialogFragment.class...
processing android/support/v7/app/AppCompatViewInflater.class...
processing android/support/v7/app/AppCompatViewInflater$DeclaredOnClickListener.class...
processing android/support/v7/app/NavItemSelectedListener.class...
processing android/support/v7/app/NotificationCompat.class...
processing android/support/v7/app/NotificationCompat$1.class...
processing android/support/v7/app/NotificationCompat$Builder.class...
processing android/support/v7/app/NotificationCompat$IceCreamSandwichExtender.class...
processing android/support/v7/app/NotificationCompat$JellybeanExtender.class...
processing android/support/v7/app/NotificationCompat$LollipopExtender.class...
processing android/support/v7/app/NotificationCompat$MediaStyle.class...
processing android/support/v7/app/NotificationCompatImpl21.class...
processing android/support/v7/app/NotificationCompatImplBase.class...
processing android/support/v7/app/ToolbarActionBar.class...
processing android/support/v7/app/ToolbarActionBar$1.class...
processing android/support/v7/app/ToolbarActionBar$2.class...
processing android/support/v7/app/ToolbarActionBar$ActionMenuPresenterCallback.class...
processing android/support/v7/app/ToolbarActionBar$MenuBuilderCallback.class...
processing android/support/v7/app/ToolbarActionBar$PanelMenuPresenterCallback.class...
processing android/support/v7/app/ToolbarActionBar$ToolbarCallbackWrapper.class...
processing android/support/v7/app/TwilightCalculator.class...
processing android/support/v7/app/TwilightManager.class...
processing android/support/v7/app/TwilightManager$1.class...
processing android/support/v7/app/TwilightManager$TwilightState.class...
processing android/support/v7/app/WindowDecorActionBar.class...
processing android/support/v7/app/WindowDecorActionBar$1.class...
processing android/support/v7/app/WindowDecorActionBar$2.class...
processing android/support/v7/app/WindowDecorActionBar$3.class...
processing android/support/v7/app/WindowDecorActionBar$ActionModeImpl.class...
processing android/support/v7/app/WindowDecorActionBar$TabImpl.class...
ignored resource android/support/v7/appcompat/
processing android/support/v7/appcompat/BuildConfig.class...
ignored resource android/support/v7/graphics/
ignored resource android/support/v7/graphics/drawable/
processing android/support/v7/graphics/drawable/DrawableUtils.class...
processing android/support/v7/graphics/drawable/DrawableWrapper.class...
processing android/support/v7/graphics/drawable/DrawerArrowDrawable.class...
processing android/support/v7/graphics/drawable/DrawerArrowDrawable$ArrowDirection.class...
ignored resource android/support/v7/text/
processing android/support/v7/text/AllCapsTransformationMethod.class...
ignored resource android/support/v7/transition/
processing android/support/v7/transition/ActionBarTransition.class...
ignored resource android/support/v7/view/
processing android/support/v7/view/ActionBarPolicy.class...
processing android/support/v7/view/ActionMode.class...
processing android/support/v7/view/ActionMode$Callback.class...
processing android/support/v7/view/CollapsibleActionView.class...
processing android/support/v7/view/ContextThemeWrapper.class...
processing android/support/v7/view/StandaloneActionMode.class...
processing android/support/v7/view/SupportActionModeWrapper.class...
processing android/support/v7/view/SupportActionModeWrapper$CallbackWrapper.class...
processing android/support/v7/view/SupportMenuInflater.class...
processing android/support/v7/view/SupportMenuInflater$InflatedOnMenuItemClickListener.class...
processing android/support/v7/view/SupportMenuInflater$MenuState.class...
processing android/support/v7/view/ViewPropertyAnimatorCompatSet.class...
processing android/support/v7/view/ViewPropertyAnimatorCompatSet$1.class...
processing android/support/v7/view/WindowCallbackWrapper.class...
ignored resource android/support/v7/view/menu/
processing android/support/v7/view/menu/ActionMenuItem.class...
processing android/support/v7/view/menu/ActionMenuItemView.class...
processing android/support/v7/view/menu/ActionMenuItemView$ActionMenuItemForwardingListener.class...
processing android/support/v7/view/menu/ActionMenuItemView$PopupCallback.class...
processing android/support/v7/view/menu/BaseMenuPresenter.class...
processing android/support/v7/view/menu/BaseMenuWrapper.class...
processing android/support/v7/view/menu/BaseWrapper.class...
processing android/support/v7/view/menu/ExpandedMenuView.class...
processing android/support/v7/view/menu/ListMenuItemView.class...
processing android/support/v7/view/menu/ListMenuPresenter.class...
processing android/support/v7/view/menu/ListMenuPresenter$MenuAdapter.class...
processing android/support/v7/view/menu/MenuBuilder.class...
processing android/support/v7/view/menu/MenuBuilder$Callback.class...
processing android/support/v7/view/menu/MenuBuilder$ItemInvoker.class...
processing android/support/v7/view/menu/MenuDialogHelper.class...
processing android/support/v7/view/menu/MenuItemImpl.class...
processing android/support/v7/view/menu/MenuItemImpl$1.class...
processing android/support/v7/view/menu/MenuItemWrapperICS.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$ActionProviderWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$CollapsibleActionViewWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$OnActionExpandListenerWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$OnMenuItemClickListenerWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperJB.class...
processing android/support/v7/view/menu/MenuItemWrapperJB$ActionProviderWrapperJB.class...
processing android/support/v7/view/menu/MenuPopupHelper.class...
processing android/support/v7/view/menu/MenuPopupHelper$MenuAdapter.class...
processing android/support/v7/view/menu/MenuPresenter.class...
processing android/support/v7/view/menu/MenuPresenter$Callback.class...
processing android/support/v7/view/menu/MenuView.class...
processing android/support/v7/view/menu/MenuView$ItemView.class...
processing android/support/v7/view/menu/MenuWrapperFactory.class...
processing android/support/v7/view/menu/MenuWrapperICS.class...
processing android/support/v7/view/menu/SubMenuBuilder.class...
processing android/support/v7/view/menu/SubMenuWrapperICS.class...
ignored resource android/support/v7/widget/
processing android/support/v7/widget/AbsActionBarView.class...
processing android/support/v7/widget/AbsActionBarView$1.class...
processing android/support/v7/widget/AbsActionBarView$VisibilityAnimListener.class...
processing android/support/v7/widget/ActionBarBackgroundDrawable.class...
processing android/support/v7/widget/ActionBarBackgroundDrawableV21.class...
processing android/support/v7/widget/ActionBarContainer.class...
processing android/support/v7/widget/ActionBarContextView.class...
processing android/support/v7/widget/ActionBarContextView$1.class...
processing android/support/v7/widget/ActionBarOverlayLayout.class...
processing android/support/v7/widget/ActionBarOverlayLayout$1.class...
processing android/support/v7/widget/ActionBarOverlayLayout$2.class...
processing android/support/v7/widget/ActionBarOverlayLayout$3.class...
processing android/support/v7/widget/ActionBarOverlayLayout$ActionBarVisibilityCallback.class...
processing android/support/v7/widget/ActionBarOverlayLayout$LayoutParams.class...
processing android/support/v7/widget/A<message truncated>`

**Comment by dotWasim** [comment]
I tried to remove the other one, same error

**Comment by mindnect** [comment]
remove plugins/android/bin folder.

**Comment by babji3** [comment]
did it fix the error???

**Comment by mindnect** [comment]
@babji3 
I guess that @dotWasim install admob_unity_plugin.unitypackage and GoogleMobileAds.unitypackage together. I did same mistake and got same error message.
now I install 'admob_unity_plugin.unitypackage' alone and it works perfect. 
no error.

**Comment by babji3** [comment]
ya me also same either we have to use googleplay services or admob , if we implement both this error show, when i removed these two jar files 
plugins/android/bin/android-support-v4.jar 
plugins/android/bin/google-play-service.jar

the build is perfect but ads is not showing..
if you get solved plz tell me.

**Comment by mindnect** [comment]
If you need googleplay sevices check https://github.com/playgameservices/play-games-plugin-for-unity 
or you can use unity admob plugin by fire base sdk version. 
https://github.com/unity-plugins/Firebase-Admob-Unity
Using firebase sdk you don't have to delete jar files.
delete those two lines in Plugins\Android\GoogleMobileAdsPlugin\AndroidManifest.xml
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" /> 
android:theme="@style/Theme.IAPTheme"/>

**Comment by babji3** [comment]
if i add firebase i dont need playservices??

**Comment by nosf009** [comment]
Hi all;

to my knowledge either Play Game Services for Unity is not yet OK for usage with this or I simply went mad. Last 8 hours I'm trying to get pass DEX error upon build, and much like people here - I had no luck, no matter what I do - best case is - it builds but cannot show ads. 

AndroidManifest is OK, can be merged/set up.
But JAR files from this package clearly conflict with Play Game Services's JAR's and it's a mess.

Also, Analytics won't work without Play Game Services (also Push etc), so right now I have games pending updates and have no other services than ads. 

Anyone solved this issue? Thanks in advance

**Comment by babji3** [comment]
ya for me also same issue, i build but no ads popup, i get ride of Admob  and now am using unity ads with GPGS. It works fine for me. I think Admob need update with this fix issue.

**Comment by unity-plugins** [comment]
Yes,It is some confict between this too plugin because gps version.I will try to fix  it.

**Comment by Austin47** [comment]
Well, I'm not sure when this issue will be resolved, but is crunch time over here so, does anyone have an alternative to getting Admob and google services to work together, Latter version or another method? Thanks in advance.

**Comment by unity-plugins** [comment]
this merged google admob ,firebase analytic,google play game https://github.com/unity-plugins/google-play-game-service-unity-plugin

**Comment by mostdeep123** [comment]
i try that API and the Rewarded Video Doesn't include in it.. only the banner and Intertitial show Up, can you fix the issue so all Admob include Banner, Intertitial, and Rewarded Video Include in it so on the Google Play Service will come along too , thank you

**Comment by unity-plugins** [comment]
OK
