### ISSUE TITLE
Rewarded video loading crash

### ISSUE THREAD

**Issue by Thornus** [unity-plugins/Unity-Admob#21]
Hello! The app crashes when the function that loads the rewarded video is called.

**Comment by unity-plugins** [comment]
Updated 2 days ago? are you used the last version?

**Comment by Thornus** [comment]
Yes, I saw "fix rewarded video crash bug" but it still happens, I downloaded the plugin yesterday.

**Comment by unity-plugins** [comment]
I think you are using an old version. I have tested the new version ,and it works well when call loadrewardvideo

**Comment by gordio** [comment]
Looks like I have the same error. But

```
10-20 17:22:16.678  2798  2798 I Ads     : Starting ad request.
10-20 17:22:16.679  2798  2798 I Ads     : Use AdRequest.Builder.addTestDevice("...xxx...") to get test ads on this device.
10-20 17:22:17.175  2798  2893 W Ads     : Could not instantiate mediation adapter: com.google.ads.mediation.unity.UnityAdapter. com.google.ads.mediation.unity.UnityAdapter
10-20 17:22:17.176  2798  2893 W Ads     : Fail to instantiate adapter com.google.ads.mediation.unity.UnityAdapter
10-20 17:22:17.176  2798  2893 W Ads     : android.os.RemoteException
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.internal.zzel.zzag(Unknown Source)
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.internal.zzel.zzae(Unknown Source)
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.internal.zzem$zza.onTransact(Unknown Source)
10-20 17:22:17.176  2798  2893 W Ads     : 	at android.os.Binder.transact(Binder.java:387)
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.ads.internal.mediation.client.d.a(:com.google.android.gms.DynamiteModulesA:94)
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.ads.internal.reward.c.b(:com.google.android.gms.DynamiteModulesA:220)
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.ads.internal.reward.mediation.j.a(:com.google.android.gms.DynamiteModulesA:1140)
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.DynamiteModulesA:19)
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.ads.internal.util.y.call(:com.google.android.gms.DynamiteModulesA:1055)
10-20 17:22:17.176  2798  2893 W Ads     : 	at com.google.android.gms.ads.internal.util.z.run(:com.google.android.gms.DynamiteModulesA:75)
10-20 17:22:17.176  2798  2893 W Ads     : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
10-20 17:22:17.176  2798  2893 W Ads     : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-20 17:22:17.176  2798  2893 W Ads     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-20 17:22:17.176  2798  2893 W Ads     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-20 17:22:17.176  2798  2893 W Ads     : 	at java.lang.Thread.run(Thread.java:818)
10-20 17:22:17.177  2798  2798 W Ads     : Failed to load ad: 3
```

P.S. I use "old" 6+ days old version.

**Comment by unity-plugins** [comment]
Permission denied ,add follow permission,and try

    android.permission.BLUETOOTH
    android.permission.READ_EXTERNAL_STORAGE
    android.permission.WRITE_EXTERNAL_STORAGE
