### ISSUE TITLE
showInterstitial crashes on (android) device

### ISSUE THREAD

**Issue by kgooble** [unity-plugins/Unity-Admob#27]
Hi, I decided to try using this since the official Google AdMob plugin didn't work.

As described in your `README.md`, I linked the `admobdemo.cs` file to a camera in the main scene. I replaced the interstitial ad unit ID. We don't have banner ads so I just put garbage in that string, that is, I called 
```ad.initAdmob("blah", "ca-app-pub-xxxx/xxxx")```

When I built for Android and clicked the "show interstitial" button, the app immediately crashed. When I looked at the logs, I saw this error:

```csharp
Caused by java.lang.NoClassDefFoundError: com.google.android.gms.ads.InterstitialAd
       at com.admob.plugin.p.b(Unknown Source)
       at com.admob.plugin.g.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Do you have any ideas about why this could happen? Thanks!

**Comment by unity-plugins** [comment]
Have you import aar and jars ? witch version unity do you using?
