### ISSUE TITLE
I use the demo code, can't load rewardedvideo, 

### ISSUE THREAD

**Issue by chenqiu1988** [unity-plugins/Unity-Admob#49]
I had used the plugin for a long time, and update the plugin in the week for rewarded video, the banner and Interstitial ad are succeed, but when i load a rewarded video, always failed. i read all the reference issue, all don't work , the error is:
BufferQueueProducer(  269): [SurfaceView](this:0x7f82bda000,id:156,api:1,p:11346,c:269) RunningBehind, queued size:2
W/Ads     (11346): Fail to instantiate adapter com.google.DummyAdapter
W/Ads     (11346): android.os.RemoteException
W/Ads     (11346):     at com.google.android.gms.internal.zzjz.zzav(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzjz.zzau(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzjz.zzas(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzns.zzaN(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzok.zza(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzok.zzco(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzpj$1.run(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzpn$2.zzbk(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzpn$2.call(Unknown Source)
W/Ads     (11346):     at com.google.android.gms.internal.zzpn$3.run(Unknown Source)
W/Ads     (11346):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/Ads     (11346):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/Ads     (11346):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/Ads     (11346):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/Ads     (11346):     at java.lang.Thread.run(Thread.java:818)
W/Ads     (11346): Failed to load ad: 3
D/Surface (11346): Surface::setBuffersDimensions(this=0xf49b5c00,w=1080,h=1920)
I/BufferQueueProducer(  269): [SurfaceView](this:0x7f82bda000,id:156,api:1,p:11346,c:269) RunningBehind, queued size:2
D/AudioFlinger_Threads(  293): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000
D/AudioFlinger_Threads(  293): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000
I/Unity   (11346): handler onRewardedVideoEvent---onAdFailedToLoad   3_ERROR_CODE_NO_FILL
I/Unity   (11346): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
I/Unity   (11346): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
I/Unity   (11346): UnityEngine.Logger:Log(LogType, Object)
I/Unity   (11346): UnityEngine.Debug:Log(Object)
I/Unity   (11346): admobdemo:onRewardedVideoEvent(String, String) (at F:\develop\svn\client\logic\unity\snake\kbe\chinese\trunk\Assets\admobdemo.cs:110)
I/Unity   (11346): admob.InnerAdmobListener:onAdmobEvent(String, String, String) (at F:\develop\svn\client\logic\unity\snake\kbe\chinese\trunk\Assets\Plugins\AdmobAPI\Admob.cs:381)
I/Unity   (11346): admob.AdmobListenerProxy:onAdmobEvent(String, String, String) (at F:\develop\svn\client\logic\unity\snake\kbe\chinese\trunk\Assets\Plugins\AdmobAPI\AdmobListenerProxy.cs:16)
I/Unity   (11346): System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
I/Unity   (11346): System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
I/Unity   (11346): System.Reflec
D/Surface (11346): Surface::setBuffersDimensions(this=0xf49b5c00,w=1080,h=1920)

**Comment by chenqiu1988** [comment]
tonight, i build for a apk, and run on android emulator, doesn't has the error, 
but when i install on my android phone(android 4.4 ), the error is existed, 
is android version lower for the plugin?

**Comment by unity-plugins** [comment]
onRewardedVideoEvent---onAdFailedToLoad 3_ERROR_CODE_NO_FILL  

no ad for you view. no fill,not code error
