### ISSUE TITLE
[IMPORTANT] Unable to convert classes to dex format!

### ISSUE THREAD

**Issue by ahmedkhalf** [unity-plugins/Unity-Admob#91]
I get this error while building to android.
Using Unity 2017.2.0f3.

**ERROR:**
CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_60\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Twist/AppData/Local/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/BuildConfig;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/IUnityAdsListener;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$FinishState;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$PlacementState;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$UnityAdsError;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/adunit/AdUnitActivity;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:313)
	at com.android.dx.command.dexer.Main.runDx(Main.java:291)
	at com.android.dx.command.dexer.Main.main(Main.java:247)
	at com.android.dx.command.Main.main(Main.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at SDKMain.main(SDKMain.java:130)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
	... 9 more
]
stdout[
processing archive C:\Users\Twist\Desktop\Unity\Evade\Evade\Temp\StagingArea\android-libraries\admoblib-release\libs\.\classes.jar...
processing com/admob/plugin/AdmobHandler.class...
processing com/admob/plugin/AdmobListenerProxy.class...
processing com/admob/plugin/AdmobNativeAd.class...
processing com/admob/plugin/AdmobNativeAd$1.class...
processing com/admob/plugin/AdmobNativeAd$2.class...
processing com/admob/plugin/AdmobNativeAd$3.class...
processing com/admob/plugin/AdmobNativeAd$4.class...
processing com/admob/plugin/AdmobUnityPlugin.class...
processing com/admob/plugin/AdmobUnityPlugin$1.class...
processing com/admob/plugin/BannerHandler.class...
processing com/admob/plugin/BannerHandler$1.class...
processing com/admob/plugin/BannerHandler$2.class...
processing com/admob/plugin/BannerHandler$3.class...
processing com/admob/plugin/BannerHandler$BannerPosition.class...
processing com/admob/plugin/BuildConfig.class...
processing com/admob/plugin/ClassicBannerHandler.class...
processing com/admob/plugin/ClassicBannerHandler$1.class...
processing com/admob/plugin/IAdmobListener.class...
processing com/admob/plugin/IAdmobNativeAdListener.class...
processing com/admob/plugin/InterstitialHandler.class...
processing com/admob/plugin/InterstitialHandler$1.class...
processing com/admob/plugin/InterstitialHandler$2.class...
processing com/admob/plugin/InterstitialHandler$3.class...
processing com/admob/plugin/NativeBannerHandler.class...
processing com/admob/plugin/NativeBannerHandler$1.class...
processing com/admob/plugin/VideoHandler.class...
processing com/admob/plugin/VideoHandler$1.class...
processing com/admob/plugin/VideoHandler$2.class...
processing com/admob/plugin/VideoHandler$3.class...
processing archive C:\Users\Twist\Desktop\Unity\Evade\Evade\Temp\StagingArea\android-libraries\play-services-ads-15.0.0\libs\.\classes.jar...
processing com/google/android/gms/ads/internal/ClientApi.class...
processing com/google/android/gms/ads/internal/gmsg/HttpClient.class...
processing com/google/android/gms/ads/internal/gmsg/HttpClient$zza.class...
processing com/google/android/gms/ads/internal/gmsg/HttpClient$zzb.class...
processing com/google/android/gms/ads/internal/gmsg/HttpClient$zzc.class...
processing com/google/android/gms/ads/internal/gmsg/HttpClient$zzd.class...
processing com/google/android/gms/ads/internal/gmsg/zza.class...
processing com/google/android/gms/ads/internal/gmsg/zzaa.class...
processing com/google/android/gms/ads/internal/gmsg/zzab.class...
processing com/google/android/gms/ads/internal/gmsg/zzac.class...
processing com/google/android/gms/ads/internal/gmsg/zzad.class...
processing com/google/android/gms/ads/internal/gmsg/zzae.class...
processing com/google/android/gms/ads/internal/gmsg/zzaf.class...
processing com/google/android/gms/ads/internal/gmsg/zzag.class...
processing com/google/android/gms/ads/internal/gmsg/zzah.class...
processing com/google/android/gms/ads/internal/gmsg/zzai.class...
processing com/google/android/gms/ads/internal/gmsg/zzb.class...
processing com/google/android/gms/ads/internal/gmsg/zzc.class...
processing com/google/android/gms/ads/internal/gmsg/zzd.class...
processing com/google/android/gms/ads/internal/gmsg/zze.class...
processing com/google/android/gms/ads/internal/gmsg/zzf.class...
processing com/google/android/gms/ads/internal/gmsg/zzg.class...
processing com/google/android/gms/ads/internal/gmsg/zzh.class...
processing com/google/android/gms/ads/internal/gmsg/zzi.class...
processing com/google/android/gms/ads/internal/gmsg/zzj.class...
processing com/google/android/gms/ads/internal/gmsg/zzk.class...
processing com/google/android/gms/ads/internal/gmsg/zzl.class...
processing com/google/android/gms/ads/internal/gmsg/zzm.class...
processing com/google/android/gms/ads/internal/gmsg/zzn.class...
processing com/google/android/gms/ads/internal/gmsg/zzo.class...
processing com/google/android/gms/ads/internal/gmsg/zzp.class...
processing com/google/android/gms/ads/internal/gmsg/zzq.class...
processing com/google/android/gms/ads/internal/gmsg/zzr.class...
processing com/google/android/gms/ads/internal/gmsg/zzs.class...
processing com/google/android/gms/ads/internal/gmsg/zzt.class...
processing com/google/android/gms/ads/internal/gmsg/zzu.class...
processing com/google/android/gms/ads/internal/gmsg/zzv.class...
processing com/google/android/gms/ads/internal/gmsg/zzw.class...
processing com/google/android/gms/ads/internal/gmsg/zzx.class...
processing com/google/android/gms/ads/internal/gmsg/zzy.class...
processing com/google/android/gms/ads/internal/gmsg/zzz.class...
processing com/google/android/gms/ads/internal/overlay/AdOverlayInfoParcel.class...
processing com/google/android/gms/ads/internal/overlay/zza.class...
processing com/google/android/gms/ads/internal/overlay/zzb.class...
processing com/google/android/gms/ads/internal/overlay/zzc.class...
processing com/google/android/gms/ads/internal/overlay/zzd.class...
processing com/google/android/gms/ads/internal/overlay/zze.class...
processing com/google/android/gms/ads/internal/overlay/zzf.class...
processing com/google/android/gms/ads/internal/overlay/zzg.class...
processing com/google/android/gms/ads/internal/overlay/zzh.class...
processing com/google/android/gms/ads/internal/overlay/zzi.class...
processing com/google/android/gms/ads/internal/overlay/zzj.class...
processing com/google/android/gms/ads/internal/overlay/zzk.class...
processing com/google/android/gms/ads/internal/overlay/zzl.class...
processing com/google/android/gms/ads/internal/overlay/zzm.class...
processing com/google/android/gms/ads/internal/overlay/zzn.class...
processing com/google/android/gms/ads/internal/overlay/zzo.class...
processing com/google/android/gms/ads/internal/overlay/zzp.class...
processing com/google/android/gms/ads/internal/overlay/zzq.class...
processing com/google/android/gms/ads/internal/overlay/zzr.class...
processing com/google/android/gms/ads/internal/overlay/zzs.class...
processing com/google/android/gms/ads/internal/overlay/zzt.class...
processing com/google/android/gms/ads/internal/overlay/zzw.class...
processing com/google/android/gms/ads/internal/overlay/zzx.class...
processing com/google/android/gms/ads/internal/overlay/zzy.class...
processing com/google/android/gms/ads/internal/zza.class...
processing com/google/android/gms/ads/internal/zzaa.class...
processing com/google/android/gms/ads/internal/zzab.class...
processing com/google/android/gms/ads/internal/zzac.class...
processing com/google/android/gms/ads/internal/zzad.class...
processing com/google/android/gms/ads/internal/zzae.class...
processing com/google/android/gms/ads/internal/zzaf.class...
processing com/google/android/gms/ads/internal/zzag.class...
processing com/google/android/gms/ads/internal/zzah.class...
processing com/google/android/gms/ads/internal/zzai.class...
processing com/google/android/gms/ads/internal/zzaj.class...
processing com/google/android/gms/ads/internal/zzak.class...
processing com/google/android/gms/ads/internal/zzal.class...
processing com/google/android/gms/ads/internal/zzam.class...
processing com/google/android/gms/ads/internal/zzan.class...
processing com/google/android/gms/ads/internal/zzao.class...
processing com/google/android/gms/ads/internal/zzap.class...
processing com/google/android/gms/ads/internal/zzaq.class...
processing com/google/android/gms/ads/internal/zzar.class...
processing com/google/android/gms/ads/internal/zzas.class...
processing com/google/android/gms/ads/internal/zzat.class...
processing com/google/android/gms/ads/internal/zzau.class...
processing com/google/android/gms/ads/internal/zzav.class...
processing com/google/android/gms/ads/internal/zzaw.class...
processing com/google/android/gms/ads/internal/zzax.class...
processing com/google/android/gms/ads/internal/zzay.class...
processing com/google/android/gms/ads/internal/zzaz.class...
processing com/google/android/gms/ads/internal/zzb.class...
processing com/google/android/gms/ads/internal/zzba.class...
processing com/google/android/gms/ads/internal/zzbb.class...
processing com/google/android/gms/ads/internal/zzbc.class...
processing com/google/android/gms/ads/internal/zzbd.class...
processing com/google/android/gms/ads/internal/zzbe.class...
processing com/google/android/gms/ads/internal/zzbf.class...
processing com/google/android/gms/ads/internal/zzbg.class...
processing com/google/android/gms/ads/internal/zzbh.class...
processing com/google/android/gms/ads/internal/zzbi.class...
processing com/google/android/gms/ads/internal/zzbj.class...
processing com/google/android/gms/ads/internal/zzbk.class...
processing com/google/android/gms/ads/internal/zzbl.class...
processing com/google/android/gms/ads/internal/zzbm.class...
processing com/google/android/gms/ads/internal/zzbn.class...
processing com/google/android/gms/ads/internal/zzbo.class...
processing com/google/android/gms/ads/internal/zzbp.class...
processing com/google/android/gms/ads/internal/zzbq.class...
processing com/google/android/gms/ads/internal/zzbr.class...
processing com/google/android/gms/ads/internal/zzbs.class...
processing com/google/android/gms/ads/internal/zzbt.class...
processing com/google/android/gms/ads/internal/zzbu.class...
processing com/google/android/gms/ads/internal/zzbv.class...
processing com/google/android/gms/ads/internal/zzbw.class...
processing com/google/android/gms/ads/internal/zzbx.class...
processing com/google/android/gms/ads/internal/zzc.class...
processing com/google/android/gms/ads/internal/zzd.class...
processing com/google/android/gms/ads/internal/zze.class...
processing com/google/android/gms/ads/internal/zzf.class...
processing com/google/android/gms/ads/internal/zzg.class...
processing com/google/android/gms/ads/internal/zzh.class...
processing com/google/android/gms/ads/internal/zzi.class...
processing com/google/android/gms/ads/internal/zzj.class...
processing com/google/android/gms/ads/internal/zzk.class...
processing com/google/android/gms/ads/internal/zzl.class...
processing com/google/android/gms/ads/internal/zzm.class...
processing com/google/android/gms/ads/internal/zzn.class...
processing com/google/android/gms/ads/internal/zzo.class...
processing com/google/android/gms/ads/internal/zzp.class...
processing com/google/android/gms/ads/internal/zzq.class...
processing com/google/android/gms/ads/internal/zzr.class...
processing com/google/android/gms/ads/internal/zzs.class...
processing com/google/android/gms/ads/internal/zzt.class...
processing com/google/android/gms/ads/internal/zzu.class...
processing com/google/android/gms/ads/internal/zzv.class...
processing com/google/android/gms/ads/internal/zzw.class...
processing com/google/android/gms/ads/internal/zzx.class...
processing com/google/android/gms/ads/internal/zzy.class...
processing com/google/android/gms/ads/internal/zzz.class...
processing com/google/android/gms/dynamite/descriptors/com/google/android/gms/ads/dynamite/ModuleDescriptor.class...
processing com/google/android/gms/internal/ads/zza.class...
processing com/google/android/gms/internal/ads/zzaa.class...
processing com/google/android/gms/internal/ads/zzaaa.class...
processing com/google/android/gms/internal/ads/zzaab.class...
processing com/google/android/gms/internal/ads/zzaac.class...
processing com/google/android/gms/internal/ads/zzaad.class...
processing com/google/android/gms/internal/ads/zzaae.class...
processing com/google/android/gms/internal/ads/zzaaf.class...
processing com/google/android/gms/internal/ads/zzaag.class...
processing com/google/android/gms/internal/ads/zzaah.class...
processing com/google/android/gms/internal/ads/zzaai.class...
processing com/google/android/gms/internal/ads/zzaaj.class...
processing com/google/android/gms/internal/ads/zzaak.class...
processing com/google/android/gms/internal/ads/zzaal.class...
processing com/google/android/gms/internal/ads/zzaam.class...
processing com/google/android/gms/internal/ads/zzaau.class...
processing com/google/android/gms/internal/ads/zzaav.class...
processing com/google/android/gms/internal/ads/zzab.class...
processing com/google/android/gms/internal/ads/zzabf.class...
processing com/google/android/gms/internal/ads/zzabg.class...
processing com/google/android/gms/internal/ads/zzabh.class...
processing com/google/android/gms/internal/ads/zzabi.class...
processing com/google/android/gms/internal/ads/zzabj.class...
processing com/google/android/gms/internal/ads/zzabk.class...
processing com/google/android/gms/internal/ads/zzabl.class...
processing com/google/android/gms/internal/ads/zzabm.class...
processing com/google/android/gms/internal/ads/zzabn.class...
processing com/google/android/gms/internal/ads/zzabo.class...
processing com/google/android/gms/internal/ads/zzabp.class...
processing com/google/android/gms/internal/ads/zzabq.class...
processing com/google/android/gms/internal/ads/zzabr.class...
processing com/google/android/gms/internal/ads/zzabs.class...
processing com/google/android/gms/internal/ads/zzabt.class...
processing com/google/android/gms/internal/ads/zzabu.class...
processing com/google/android/gms/internal/ads/zzabv.class...
processing com/google/android/gms/internal/ads/zzabw.class...
processing com/google/android/gms/internal/ads/zzabx.class...
processing com/google/android/gms/internal/ads/zzaby.class...
processing com/google/android/gms/internal/ads/zzabz.class...
processing com/google/android/gms/internal/ads/zzac.class...
processing com/google/android/gms/internal/ads/zzaca.class...
processing com/google/android/gms/internal/ads/zzacb.class...
processing com/google/android/gms/internal/ads/zzacc.class...
processing com/google/android/gms/internal/ads/zzacd.class...
processing com/google/android/gms/internal/ads/zzace.class...
processing com/google/android/gms/internal/ads/zzacf.class...
processing com/google/android/gms/internal/ads/zzacg.class...
processing com/google/android/gms/internal/ads/zzach.class...
processing com/google/android/gms/internal/ads/zzaci.class...
processing com/google/android/gms/internal/ads/zzacj.class...
proce -message truncated-

**I need help as fast as possible.**

**Comment by unity-plugins** [comment]
Remove UnityAds.jar

**Comment by unity-plugins** [comment]
unity-ads-sdk-2.1.aar
and unity-adapter-2.1.0.0.aar

**Comment by abdulmeLINK** [comment]
Hi,
I tried solve this erorr since 25.01.2019.
You need delete unity-ads-sdk-2.1.aar and unity-adapter-2.1.0.0.aar it is worked.
Admob plugin developers need to solve this problem to next version.
